spring:
  application:
    name: @project.name@

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
      percentiles:
        http.server.requests: 0.95,0.99,1.00
        http.client.requests: 0.95,0.99,1.00
#    enable:
#      http:
#        client:
#          requests: true
#        server:
#          requests: true

